- hosts: all
  become: yes
  vars:
    default_path: /etc/nginx/sites-available/default
    custom_file: templates/custom.cfg
  tasks:
    - shell: date +%Y%m%d%H%M%S
      register: dateTime
    - name: Install latest nginx version using apt
      apt: name=nginx state=latest update_cache=true
    - name: Register default site stat
      stat: path="{{ default_path }}"
      register: nginxDefault  
    - name: Backup default site config
      copy: remote_src=yes src="{{ default_path }}" dest="{{ default_path }}_{{ dateTime.stdout }}"
      when: nginxDefault.stat.exists == True 
    - name: Copy custom site configurations
      copy: src="{{ custom_file }}" dest="{{ default_path }}"
      when: nginxDefault.stat.exists == True      
    - name: Set custom Index page
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from SJSU-{{ansible_hostname}}"
    - name: Restart nginx service
      service: name=nginx state=restarted
